### ISSUE TITLE
Problem with Types

### ISSUE THREAD

**Issue by cezl** [mostjs/hold#29]
Hey, guys!

I installed @most/hold last version (3.0.0) and for some reason the type definition file seems to be out-of-date. In this way, it raises the following error while building my code:

```
node_modules/@most/hold/type-definitions/hold.d.ts:1:59 - error TS2307: Cannot find module 'most'.

1 import {Stream, Source, Sink, Scheduler, Disposable} from "most";
```
I've checked the commits, and the above import was in fact present in hold.d.ts until the commit 15ee95c061ce7b88a2adc6935b5ab82c8acc271c

**Comment by briancavalier** [comment]
Hey @cezl.  Oh my, it appears `@most/hold` 3.0.0 was published with an old TS type definition file, and that we fixed it in git, but then didn't close the loop and publish a 3.0.1.  #25 contains the fix, and was previously reviewed and merged, so I'll release that as 3.0.1 shortly.

**Comment by briancavalier** [comment]
Just published 3.0.1 with the fixed TS type defs from #25.  Please let us know if it works for you.  Thanks!

**Comment by cezl** [comment]
Thanks, @briancavalier!
The problem with type defs was solved (:

**Comment by briancavalier** [comment]
🎉
