### ISSUE TITLE
Documentation precision

### ISSUE THREAD

**Issue by AlexGalays** [mostjs/hold#8]
"Deliver the most recently seen event to each new observer the instant it begins observing"

This sentence could make someone think the observer will observe a value synchronously when it doesn't ? (setTimeout(fn, 0) so could be anywhere between 1 and 10ms)

**Comment by briancavalier** [comment]
The blanket assumption for all most.js streams is that events will *never* be delivered in the same call stack as the one where you begin to observe them.  We should probably do a better job of making *that* obvious in the core most.js docs.  I'll add an issue for that.

Do you think we still need to repeat it here?

> (setTimeout(fn, 0) so could be anywhere between 1 and 10ms)

Technically, it uses a faster mechanism (promises, which typically use a micro-tick queue, whereas setTimeout uses a macro-tick queue) than setTimeout.

**Comment by AlexGalays** [comment]
Alright, if the core most.js docs mentioned it, it would work too.

**Comment by briancavalier** [comment]
> Alright, if the core most.js docs mentioned it, it would work too.

Sounds good.  Thanks for bringing this up.  It definitely could be more clear in the core docs.

**Comment by briancavalier** [comment]
See https://github.com/cujojs/most/issues/230
